### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by RowenTey** [planetscale/connection-examples#10]
I'm trying to directly connect to the database via DSN from Go Fiber server with Gorm but I keep getting this error:

```
2022/09/13 17:33:21 C:/Users/server/database/connect.go:19
[error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.
```

Here's how my DSN string looks like:
```
DSN=user:pass@tcp(ap-southeast.connect.psdb.cloud)/database?tls=true
```

And the code for connecting to the database looks like:
```
dsn := config.Config("DATABASE_URL")
DB, err = gorm.Open(mysql.Open(dsn), &gorm.Config{
   DisableForeignKeyConstraintWhenMigrating: true,
})
if err != nil {
  fmt.Println("Failed to connect database")
  log.Fatal(err)
}
fmt.Println("Connection opened to Database")
```

I suspect it's something going on with my Firewall but I'm not entirely sure. Any advice/help would be greatly appreciated!

**Comment by nohu98com** [comment]
> Tôi đang cố gắng kết nối trực tiếp tới cơ sở dữ liệu thông qua DSN từ máy chủ Go Fiber bằng Gorm nhưng tôi cứ gặp lỗi này:
> 
> ```
> 2022/09/13 17:33:21 C:/Users/server/database/connect.go:19
> [error] failed to initialize database, got error dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.
> ```
> 
> Chuỗi DSN của tôi trông như thế này:
> 
> ```
> DSN=user:pass@tcp(ap-southeast.connect.psdb.cloud)/database?tls=true
> ```
> 
> Và mã để kết nối với cơ sở dữ liệu trông như thế này:
> 
> ```
> dsn := config.Config("DSN")
> DB, err = gorm.Open(mysql.Open(dsn), &gorm.Config{
>    DisableForeignKeyConstraintWhenMigrating: true,
> })
> if err != nil {
>   fmt.Println("Failed to connect database")
>   log.Fatal(err)
> }
> fmt.Println("Connection opened to Database")
> ```
> 
> Tôi nghi ngờ có vấn đề gì đó với Tường lửa của tôi nhưng tôi không chắc lắm. Bất kỳ lời khuyên/trợ giúp nào cũng sẽ được đánh giá cao!

https://github.com/planetscale/connection-examples/issues/10#issue-1371160162
